DROP TABLE IF EXISTS tasks;

CREATE TABLE tasks (
                       id BIGINT PRIMARY KEY AUTO_INCREMENT,
                       description VARCHAR(100) NOT NULL,
                       status VARCHAR(20) NOT NULL DEFAULT 'IN_PROGRESS',
                       created_at TIMESTAMP NOT NULL,
                       updated_at TIMESTAMP NOT NULL
);

-- Add constraint for enum values
ALTER TABLE tasks ADD CONSTRAINT status_check
    CHECK (status IN ('IN_PROGRESS', 'DONE', 'PAUSED'));

-- Insert sample data (without IDs and with proper enum values)
INSERT INTO tasks (description, status, created_at, updated_at) VALUES
                                                                    ('Write project proposal', 'DONE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Review code with team', 'PAUSED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Implement login feature', 'IN_PROGRESS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Fix UI bugs on dashboard', 'DONE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Prepare test cases', 'PAUSED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Write documentation', 'IN_PROGRESS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Deploy app to staging', 'DONE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Set up CI/CD pipeline', 'PAUSED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Integrate payment gateway', 'IN_PROGRESS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Update user roles module', 'DONE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Create demo presentation', 'PAUSED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Refactor API endpoints', 'IN_PROGRESS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Test mobile responsiveness', 'DONE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Conduct user interviews', 'PAUSED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Optimize database queries', 'IN_PROGRESS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Analyze server logs', 'DONE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Design onboarding flow', 'PAUSED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Build notification system', 'IN_PROGRESS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Set up monitoring tools', 'DONE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Migrate legacy data', 'PAUSED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Draft technical blog post', 'IN_PROGRESS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Schedule sprint planning', 'DONE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Organize team retro', 'PAUSED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Clean up dead code', 'IN_PROGRESS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Audit app security', 'DONE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Improve search algorithm', 'PAUSED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Review pull requests', 'IN_PROGRESS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Enable dark mode', 'DONE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Write unit tests', 'PAUSED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Implement 2FA login', 'IN_PROGRESS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Update landing page', 'DONE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Set up Docker containers', 'PAUSED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Add email notifications', 'IN_PROGRESS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Fix broken links', 'DONE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Draft privacy policy', 'PAUSED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Automate backups', 'IN_PROGRESS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Tune app performance', 'DONE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Create FAQs section', 'PAUSED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Update API docs', 'IN_PROGRESS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Plan feature roadmap', 'DONE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Create team wiki', 'PAUSED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Test third-party APIs', 'IN_PROGRESS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Improve error handling', 'DONE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Refine user feedback flow', 'PAUSED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Design mobile layout', 'IN_PROGRESS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Fix mobile nav bar', 'DONE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Schedule product demo', 'PAUSED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Benchmark load times', 'IN_PROGRESS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Enable multi-language support', 'DONE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Customize 404 page', 'PAUSED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Add loading spinners', 'IN_PROGRESS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Fix typos in footer', 'DONE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Add analytics tracking', 'PAUSED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Test login with OAuth', 'IN_PROGRESS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Fix caching issues', 'DONE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Write integration tests', 'PAUSED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Prepare release notes', 'IN_PROGRESS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Polish product tour', 'DONE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Fix font rendering bug', 'PAUSED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Tweak color palette', 'IN_PROGRESS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Redesign settings page', 'DONE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Build export to CSV', 'PAUSED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Review performance reports', 'IN_PROGRESS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Create signup flow animation', 'DONE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Fix broken image links', 'PAUSED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Test file upload feature', 'IN_PROGRESS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Create onboarding checklist', 'DONE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Design notification icons', 'PAUSED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Implement role-based access', 'IN_PROGRESS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Build user activity log', 'DONE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Test push notifications', 'PAUSED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Refactor frontend code', 'IN_PROGRESS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Optimize page transitions', 'DONE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Fix scrollbar styling', 'PAUSED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Write e2e tests', 'IN_PROGRESS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Generate sitemap.xml', 'DONE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Update legal disclaimer', 'PAUSED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Fix memory leaks', 'IN_PROGRESS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Improve form validation', 'DONE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Implement lazy loading', 'PAUSED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Test localization strings', 'IN_PROGRESS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Review accessibility issues', 'DONE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Create changelog', 'PAUSED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Add markdown support', 'IN_PROGRESS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Create admin panel UI', 'DONE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Fix table alignment', 'PAUSED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Enable email verification', 'IN_PROGRESS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Improve onboarding UX', 'DONE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Test expired session flow', 'PAUSED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Track user activity', 'IN_PROGRESS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Implement autocomplete', 'DONE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Update font family', 'PAUSED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Remove deprecated code', 'IN_PROGRESS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Test profile picture upload', 'DONE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Fix z-index stacking bug', 'PAUSED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Create error message templates', 'IN_PROGRESS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                    ('Build theme switcher', 'DONE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- ... rest of your sample data ...